version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - ued
  ued:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ued
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    depends_on:
      - db
      - redis
    environment:
      - "PORT=8080"
      - "POSTGRESQL_URL=host=db user=root password=ued#2020 dbname=ued sslmode=disable"
      - "JWT_SECRET=hkD7lRPQSTP9VNs1ACI2y8UWaT1fa8LTS2pvnNWSRS6sQw4Wvt"
      - "REDIS_URL=redis:6379"
      - "APP_URL=https://ued.tabvn.com"
      - "API_URL=https://ued.tabvn.com/api"
    networks:
      - ued
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: ued
      POSTGRES_PASSWORD: ued#2020
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
    volumes:
      - ./data:/var/lib/postgresql/data
      - /tmp:/tmp
    ports:
      - 5432:5432
    networks:
      - ued
  redis:
    restart: always
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - ued
networks:
  ued:
    driver: bridge
